### ISSUE TITLE
`NewContext passed an unknown http.Request` with appengine context

### ISSUE THREAD

**Issue by akm** [goadesign/examples#32]
[I'm trying to add a test with appengine context](https://github.com/goadesign/examples/pull/31) introduced in [app engine document](https://cloud.google.com/appengine/docs/standard/go/tools/localunittesting/#Go_Introducing_the_aetest_package).
but it doesn't work because appengine returns an error `appengine: NewContext passed an unknown http.Request`.

I can make the test passed by [overwriting generated source code](https://github.com/goadesign/examples/pull/31/commits/d975258e584e6f831f5d9f262c774da69d9dc057) but it should not be done.
Could you tell me how I should do?

**Comment by raphael** [comment]
Unfortunately I don't see an easy way to do that without breaking backwards compatibility. Maybe the generated code could produce alternate functions that accept a HTTP request and configure it but that's a big change for a fairly narrow use case.

Test generation is a TBD in v2 and the idea is to do it as a plugin rather than something built into the goa core packages. I'd be happy to help you come up with a v2 plugin that generates test code that is compatible with the app engine test package.

**Comment by akm** [comment]
Thank you for your reply.
I understand that it is difficult with v1.
I recently started using Goa, so I'll catch up with v2.
Thank you.
